/**
 * Partner Expansion Data - v3.1 (PT3)
 *
 * Data source: PARTNER_EXPANSION_RESEARCH_PT3.md
 * Last updated: 2026-01-31
 *
 * v3.1 (PT3) Changes:
 * - Expanded from 50 to 68 partners based on X/Twitter sentiment analysis
 * - Added X hype signal tracking (viral posts from @fireship_dev, @ThePrimeagen, @sidi_jeddou_dev, etc.)
 * - New primitives added:
 *   - Workflow Automation & Integrations (Zapier, Make, n8n)
 *   - AI Model Inference & Hosting (Replicate, Hugging Face, Groq)
 *   - Security & Vulnerability Scanning (Snyk, Socket, Dependabot)
 *   - Documentation Generation (Mintlify, Docusaurus, Readme.io)
 *   - BaaS / Firebase Alternatives (Appwrite, PocketBase, Firebase)
 *   - AI Web Scraping & Semantic Search (Firecrawl, Exa, Jina AI)
 */

const DATA_VERSION = "2026-01-31-v3.1-PT3";

/**
 * Partner Schema:
 * {
 *   id: number,
 *   name: string,
 *   url: string,                 // Company website URL
 *   xHandle: string|null,        // Company X/Twitter handle (without @)
 *   founderX: string|null,       // Founder/CEO X handle (without @)
 *   devRelX: string|null,        // Dev Rel / Developer Advocate X handle (without @)
 *   primitive: string,           // Category/use case
 *   tier: number,                // 1-5 (1 = highest conviction)
 *   confidence: string,          // "Very High" | "High" | "Medium-High" | "Medium"
 *   brief: string,               // One-sentence description of the offering
 *   evidence: string,            // Key evidence supporting selection
 *   apiReady: boolean,           // Has provisioning-ready API
 *   cliAvailable: boolean,       // Has CLI tool
 *   openSource: boolean,         // Is OSS or has major OSS component
 *   metrics: string,             // Key metrics (stars, downloads, etc.)
 *   launchPartnerOverlap: boolean,  // Overlaps with existing launch partner category
 *   boilerplateCount: number,    // Count of boilerplates including this tool (out of 15)
 *   vcValidation: boolean,       // Named in major VC market maps
 *   analystMention: boolean,     // Appears in Gartner/Forrester/ThoughtWorks
 *   benchmarkWinner: boolean,    // Won category benchmark comparison
 *   xHype: boolean,              // High engagement on X (viral posts, influencer mentions)
 *   isNew: boolean               // New in PT3
 * }
 */

const PARTNERS = [
  // ============================================
  // TIER 1: Highest Conviction (12 partners)
  // ============================================
  { id: 1, name: "Stripe", url: "https://stripe.com", xHandle: "stripe", founderX: "patrickc", devRelX: null, primitive: "Payments", tier: 1, confidence: "Very High", brief: "Complete payments infrastructure with subscriptions, invoicing, and global payouts via unified API.", evidence: "13/15 boilerplates; Wing ET30 GIGA tier; universal default", apiReady: true, cliAvailable: true, openSource: false, metrics: "13/15 boilerplates; dominant", launchPartnerOverlap: false, boilerplateCount: 13, vcValidation: true, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 2, name: "Cloudflare", url: "https://cloudflare.com", xHandle: "Cloudflare", founderX: "eastdakota", devRelX: "lizziepika", primitive: "Edge Compute/Storage/CDN", tier: 1, confidence: "Very High", brief: "Global edge network with serverless compute (Workers), R2 storage, and zero-egress CDN.", evidence: "Redpoint InfraRed; zero-egress; frequent X praise for Workers AI", apiReady: true, cliAvailable: true, openSource: false, metrics: "330+ edge PoPs; public company", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: true, analystMention: true, benchmarkWinner: false, xHype: true, isNew: false },
  { id: 3, name: "Twilio", url: "https://twilio.com", xHandle: "twilio", founderX: "jeffiel", devRelX: null, primitive: "SMS/Voice/Comms", tier: 1, confidence: "Very High", brief: "Programmable SMS, voice, video, and WhatsApp APIs for global communications.", evidence: "Bessemer portfolio success; #2 Brex startup spend; global SMS leader", apiReady: true, cliAvailable: true, openSource: false, metrics: "#2 Brex startup spend", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: true, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 4, name: "Datadog", url: "https://datadoghq.com", xHandle: "datadoghq", founderX: "oliveur", devRelX: null, primitive: "Observability", tier: 1, confidence: "Very High", brief: "Unified monitoring platform for metrics, logs, traces, and APM with 600+ integrations.", evidence: "Gartner MQ Leader (5th year); Brex top-5; 50% MoM growth", apiReady: true, cliAvailable: true, openSource: false, metrics: "Gartner Leader; Brex top-5", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: true, analystMention: true, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 5, name: "MongoDB Atlas", url: "https://mongodb.com/atlas", xHandle: "MongoDB", founderX: null, devRelX: "Didicodes", primitive: "Database", tier: 1, confidence: "Very High", brief: "Managed document database with flexible schema, full-text search, and multi-cloud deployment.", evidence: "Gartner MQ Leader (4th year); Vercel + Netlify native; #1 NoSQL", apiReady: true, cliAvailable: true, openSource: true, metrics: "26K+ stars; Gartner Leader", launchPartnerOverlap: true, boilerplateCount: 1, vcValidation: false, analystMention: true, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 6, name: "LaunchDarkly", url: "https://launchdarkly.com", xHandle: "launchdarkly", founderX: "edaboroughs", devRelX: "annthurium", primitive: "Feature Flags", tier: 1, confidence: "Very High", brief: "Enterprise feature management with targeting rules, experimentation, and progressive rollouts.", evidence: "Bessemer portfolio; Forrester Strong Performer; Gartner Hype Cycle featured", apiReady: true, cliAvailable: true, openSource: false, metrics: "Billions of evaluations daily", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: true, analystMention: true, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 7, name: "Auth0", url: "https://auth0.com", xHandle: "auth0", founderX: null, devRelX: "deepu105", primitive: "Auth & Identity", tier: 1, confidence: "Very High", brief: "Identity platform with SSO, MFA, social login, and customizable authentication flows.", evidence: "Bessemer portfolio success; Netlify partner; 7.5K free MAUs", apiReady: true, cliAvailable: true, openSource: false, metrics: "9K+ stars (SDK); enterprise", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: true, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 8, name: "Upstash", url: "https://upstash.com", xHandle: "upstash", founderX: "enesakar", devRelX: null, primitive: "Serverless Redis/Kafka/Queue", tier: 1, confidence: "Very High", brief: "Serverless Redis, Kafka, and QStash with per-request pricing and global replication.", evidence: "Vercel native (KV); v0.dev auto-provision; Terraform/Pulumi support", apiReady: true, cliAvailable: true, openSource: false, metrics: "Vercel Marketplace native", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 9, name: "Prisma", url: "https://prisma.io", xHandle: "prisma", founderX: "schickling", devRelX: "nikolasburk", primitive: "ORM & Data Access", tier: 1, confidence: "Very High", brief: "Type-safe ORM with auto-generated queries, migrations, and visual database browser.", evidence: "10/15 boilerplates; Vercel Marketplace (Prisma Postgres); 5.1M npm/wk", apiReady: true, cliAvailable: true, openSource: true, metrics: "45K+ stars; 5.1M npm/wk", launchPartnerOverlap: true, boilerplateCount: 10, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 10, name: "Payload CMS", url: "https://payloadcms.com", xHandle: "payloadcms", founderX: "JamesMikrut", devRelX: null, primitive: "CMS", tier: 1, confidence: "Very High", brief: "Code-first headless CMS with TypeScript config, built-in auth, and self-hosting option.", evidence: "7x faster than Strapi (benchmark); 30K+ stars; steepest GitHub growth", apiReady: true, cliAvailable: true, openSource: true, metrics: "30K+ stars; 7x faster", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: true, xHype: false, isNew: false },
  { id: 11, name: "Zapier", url: "https://zapier.com", xHandle: "zapier", founderX: "wadefoster", devRelX: null, primitive: "Workflow Automation", tier: 1, confidence: "Very High", brief: "No-code automation platform connecting 6,000+ apps with triggers, actions, and multi-step workflows.", evidence: "@fireship_dev viral (12K+ likes): 'Zapier still king for connecting everything'", apiReady: true, cliAvailable: false, openSource: false, metrics: "12K+ likes; universal automation", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },
  { id: 12, name: "Replicate", url: "https://replicate.com", xHandle: "replicate", founderX: "bfirsh", devRelX: null, primitive: "AI Model Inference", tier: 1, confidence: "Very High", brief: "Run open-source ML models via API with automatic scaling and pay-per-second billing.", evidence: "@krunalexplores, @sidi_jeddou_dev: 'run models without infra pain'", apiReady: true, cliAvailable: true, openSource: false, metrics: "Top AI inference platform", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },

  // ============================================
  // TIER 2: Strong Conviction (15 partners)
  // ============================================
  { id: 13, name: "Inngest", url: "https://inngest.com", xHandle: "inngest", founderX: "itstonyhb", devRelX: "atticjack", primitive: "Workers & Background Jobs", tier: 2, confidence: "High", brief: "Event-driven serverless functions with automatic retries, scheduling, and step orchestration.", evidence: "ThoughtWorks 'Trial'; 100M+ daily executions; event-driven functions", apiReady: true, cliAvailable: false, openSource: true, metrics: "5K+ stars; 100M+ daily", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: true, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 14, name: "Deepgram", url: "https://deepgram.com", xHandle: "deepgramai", founderX: null, devRelX: "lukeocodes", primitive: "Voice & Speech AI", tier: 2, confidence: "High", brief: "Real-time speech-to-text API with industry-leading accuracy and 118ms latency.", evidence: "118ms TTFT (benchmark winner); +127% YoY Brex; Nova-3: 6.84% WER", apiReady: true, cliAvailable: false, openSource: false, metrics: "+127% YoY; 118ms latency", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: true, xHype: false, isNew: false },
  { id: 15, name: "ElevenLabs", url: "https://elevenlabs.io", xHandle: "elevenlabsio", founderX: null, devRelX: null, primitive: "Voice & Speech AI", tier: 2, confidence: "High", brief: "AI voice synthesis with ultra-realistic TTS, voice cloning, and dubbing in 29 languages.", evidence: "75ms Flash v2.5 (38x faster than OpenAI TTS); Wing ET30 LATE tier", apiReady: true, cliAvailable: false, openSource: false, metrics: "Top-10 Brex AI; 75ms TTS", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: true, analystMention: false, benchmarkWinner: true, xHype: false, isNew: false },
  { id: 16, name: "Railway", url: "https://railway.com", xHandle: "Railway", founderX: "JustJake", devRelX: null, primitive: "Hosting & Compute", tier: 2, confidence: "High", brief: "Developer-first PaaS with instant deployments, one-click databases, and usage-based pricing.", evidence: "CLI-first; strong indie adoption; one-click DB deploy; usage-based", apiReady: true, cliAvailable: true, openSource: false, metrics: "Strong indie adoption", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 17, name: "Trigger.dev", url: "https://trigger.dev", xHandle: "triggerdotdev", founderX: "mattaitken", devRelX: null, primitive: "Workers & Background Jobs", tier: 2, confidence: "High", brief: "TypeScript-first background jobs with long-running tasks, cron, and managed serverless compute.", evidence: "ThoughtWorks 'Trial'; 10K+ stars; 'easier Temporal'; managed compute", apiReady: true, cliAvailable: true, openSource: true, metrics: "10K+ GitHub stars", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: true, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 18, name: "Turso", url: "https://turso.tech", xHandle: "taborchers", founderX: "glcst", devRelX: null, primitive: "Database", tier: 2, confidence: "High", brief: "Edge-native SQLite database with <130ms global latency and embedded replicas.", evidence: "<130ms edge latency (benchmark winner); ThoughtWorks 'Trial'; Netlify partner", apiReady: true, cliAvailable: true, openSource: true, metrics: "12K+ stars; <130ms edge", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: true, benchmarkWinner: true, xHype: false, isNew: false },
  { id: 19, name: "Meilisearch", url: "https://meilisearch.com", xHandle: "meilisearch", founderX: null, devRelX: "clurquizar", primitive: "Search", tier: 2, confidence: "High", brief: "Lightning-fast, typo-tolerant search engine with hybrid keyword + vector search support.", evidence: "54K+ stars; Rust-based; hybrid keyword+vector search; $30/mo Build tier", apiReady: true, cliAvailable: false, openSource: true, metrics: "54K+ GitHub stars", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 20, name: "Sanity", url: "https://sanity.io", xHandle: "sanity_io", founderX: "even", devRelX: "kmelve", primitive: "CMS", tier: 2, confidence: "High", brief: "Composable content platform with real-time collaboration, GROQ query language, and customizable studio.", evidence: "G2 #1 (4 consecutive years); 2/15 boilerplates; Vercel + Netlify partner", apiReady: true, cliAvailable: true, openSource: false, metrics: "#1 G2 headless CMS", launchPartnerOverlap: false, boilerplateCount: 2, vcValidation: false, analystMention: true, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 21, name: "Axiom", url: "https://axiom.co", xHandle: "AxiomFM", founderX: "njpatel", devRelX: "seiflotfy", primitive: "Observability", tier: 2, confidence: "High", brief: "Serverless log management with unlimited data retention, zero indexing, and instant queries.", evidence: "Vercel Marketplace native; developer-first pricing; Theo/t3gg recommended", apiReady: true, cliAvailable: true, openSource: false, metrics: "Vercel Marketplace partner", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 22, name: "Fly.io", url: "https://fly.io", xHandle: "flydotio", founderX: "mrkurt", devRelX: null, primitive: "Hosting & Compute", tier: 2, confidence: "High", brief: "Run Docker containers as micro-VMs globally with sub-second deployments and built-in Postgres.", evidence: "flyctl CLI; globally distributed micro-VMs; container-based", apiReady: true, cliAvailable: true, openSource: false, metrics: "3K+ stars (flyctl)", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 23, name: "Hugging Face", url: "https://huggingface.co", xHandle: "huggingface", founderX: "julien_c", devRelX: null, primitive: "AI Model Inference", tier: 2, confidence: "High", brief: "AI model hub with 500K+ models, datasets, Spaces for deployment, and Inference API.", evidence: "@fireship_dev OSS list; 'playground for open AI'; massive community buzz", apiReady: true, cliAvailable: true, openSource: true, metrics: "Largest AI model hub", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: true, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },
  { id: 24, name: "Snyk", url: "https://snyk.io", xHandle: "snyksec", founderX: null, devRelX: null, primitive: "Security & Vulnerability", tier: 2, confidence: "High", brief: "Developer security platform scanning code, dependencies, containers, and IaC for vulnerabilities.", evidence: "DevOps toolkit threads: 'Snyk for DevSecOps'; repeated in indie security discussions", apiReady: true, cliAvailable: true, openSource: false, metrics: "DevSecOps leader", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },
  { id: 25, name: "Appwrite", url: "https://appwrite.io", xHandle: "appwrite", founderX: "eldadfux", devRelX: "christyjacob4", primitive: "BaaS / Firebase Alternative", tier: 2, confidence: "High", brief: "Open-source backend platform with auth, database, storage, functions, and realtime out of the box.", evidence: "@sidi_jeddou_dev (2.8K likes): 'cool backend framework'; 'self-hosted Supabase alt'", apiReady: true, cliAvailable: true, openSource: true, metrics: "40K+ GitHub stars", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },
  { id: 26, name: "Firebase", url: "https://firebase.google.com", xHandle: "Firebase", founderX: null, devRelX: null, primitive: "BaaS / Firebase Alternative", tier: 2, confidence: "High", brief: "Google's app development platform with Firestore, Auth, Hosting, Cloud Functions, and Analytics.", evidence: "@fireship_dev (12K+ likes): 'still undefeated for MVP speed'; Google-backed", apiReady: true, cliAvailable: true, openSource: false, metrics: "12K+ likes; MVP standard", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },
  { id: 27, name: "Firecrawl", url: "https://firecrawl.dev", xHandle: null, founderX: "ericciarla", devRelX: "nickscamara_", primitive: "AI Web Scraping", tier: 2, confidence: "High", brief: "Web scraping API that converts websites to clean markdown for LLM ingestion.", evidence: "@sidi_jeddou_dev viral (2.8K likes): 'best and fastest scraper'", apiReady: true, cliAvailable: false, openSource: true, metrics: "2.8K likes; fastest scraper", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },

  // ============================================
  // TIER 3: Good Conviction (15 partners)
  // ============================================
  { id: 28, name: "Drizzle ORM", url: "https://orm.drizzle.team", xHandle: "DrizzleORM", founderX: "_alexblokh", devRelX: null, primitive: "ORM & Data Access", tier: 3, confidence: "High", brief: "Lightweight TypeScript ORM with SQL-like syntax, zero dependencies, and edge runtime support.", evidence: "ThoughtWorks 'Trial'; 6/15 boilerplates; edge-optimized (~7kb)", apiReady: true, cliAvailable: true, openSource: true, metrics: "32K+ stars; 2.3M npm/wk", launchPartnerOverlap: false, boilerplateCount: 6, vcValidation: false, analystMention: true, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 29, name: "PlanetScale", url: "https://planetscale.com", xHandle: "planetscale", founderX: "samlambert", devRelX: null, primitive: "Database", tier: 3, confidence: "High", brief: "Serverless MySQL platform built on Vitess with database branching and non-blocking schema changes.", evidence: "~35K QPS (benchmark throughput winner); Vitess-based; database branching", apiReady: true, cliAvailable: true, openSource: false, metrics: "~35K QPS; branching pioneer", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: true, xHype: false, isNew: false },
  { id: 30, name: "Novu", url: "https://novu.co", xHandle: "novuhq", founderX: "dimagrossman", devRelX: "pearce_emil", primitive: "Notifications", tier: 3, confidence: "High", brief: "Open-source notification infrastructure for email, SMS, push, in-app, and chat in one API.", evidence: "38K+ stars (MIT); unified multi-channel: email, SMS, push, in-app, chat", apiReady: true, cliAvailable: false, openSource: true, metrics: "38K+ GitHub stars", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 31, name: "Render", url: "https://render.com", xHandle: "render", founderX: "anuraggoel", devRelX: null, primitive: "Hosting & Compute", tier: 3, confidence: "Medium-High", brief: "Unified cloud platform for web services, static sites, cron jobs, and managed databases.", evidence: "Bessemer portfolio; Blueprint spec for declarative infra; Heroku replacement", apiReady: true, cliAvailable: false, openSource: false, metrics: "Heroku migration wave", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: true, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 32, name: "Qdrant", url: "https://qdrant.tech", xHandle: "qdrant_engine", founderX: "generall931", devRelX: null, primitive: "Vector DB & AI Infra", tier: 3, confidence: "Medium-High", brief: "High-performance vector database in Rust with filtering, payload storage, and 2x Pinecone throughput.", evidence: "326 QPS vs Pinecone 150 QPS (benchmark 2:1 winner); Rust; 1GB free forever", apiReady: true, cliAvailable: false, openSource: true, metrics: "9K+ stars; 2x Pinecone perf", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: true, xHype: false, isNew: false },
  { id: 33, name: "GrowthBook", url: "https://growthbook.io", xHandle: "growth_book", founderX: null, devRelX: null, primitive: "Feature Flags", tier: 3, confidence: "Medium-High", brief: "Open-source feature flagging and A/B testing platform with Bayesian statistics engine.", evidence: "6K+ stars; Bayesian stats engine; feature flags + A/B testing; self-host or managed", apiReady: true, cliAvailable: false, openSource: true, metrics: "6K+ GitHub stars", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 34, name: "Strapi", url: "https://strapi.io", xHandle: "strapijs", founderX: null, devRelX: null, primitive: "CMS", tier: 3, confidence: "Medium-High", brief: "Leading open-source headless CMS with plugin marketplace, REST/GraphQL APIs, and admin panel.", evidence: "60K+ stars; 350+ plugins; REST + GraphQL + CLI (but 7x slower than Payload)", apiReady: true, cliAvailable: true, openSource: true, metrics: "60K+ stars; OSS leader", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 35, name: "Typesense", url: "https://typesense.org", xHandle: "typesense", founderX: "jasonbosco", devRelX: null, primitive: "Search", tier: 3, confidence: "Medium-High", brief: "Fast, typo-tolerant search engine built in C++ with sub-50ms results and easy setup.", evidence: "24K+ stars; C++; <50ms results; free self-hosted; managed from $19/mo", apiReady: true, cliAvailable: false, openSource: true, metrics: "24K+ GitHub stars", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 36, name: "Netlify", url: "https://netlify.com", xHandle: "netlify", founderX: "biilmann", devRelX: null, primitive: "Hosting & Compute", tier: 3, confidence: "Medium-High", brief: "Jamstack platform with instant rollbacks, deploy previews, edge functions, and 300+ integrations.", evidence: "Bessemer Cloud 100 newcomer; rich integration catalog; deploy previews", apiReady: true, cliAvailable: true, openSource: false, metrics: "Major platform", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: true, analystMention: true, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 37, name: "CockroachDB", url: "https://cockroachlabs.com", xHandle: "CockroachDB", founderX: null, devRelX: null, primitive: "Database", tier: 3, confidence: "Medium-High", brief: "Distributed SQL database with PostgreSQL compatibility, automatic sharding, and geo-partitioning.", evidence: "30K+ stars; PostgreSQL-compatible; distributed by default; vector indexing v25.2", apiReady: true, cliAvailable: true, openSource: true, metrics: "30K+ GitHub stars", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 38, name: "Mintlify", url: "https://mintlify.com", xHandle: "mintlify", founderX: "handotdev", devRelX: null, primitive: "Documentation", tier: 3, confidence: "Medium-High", brief: "AI-powered documentation platform with beautiful templates, search, and auto-generated API docs.", evidence: "@sidi_jeddou_dev viral (2.8K likes): 'I will never build docs again – there's Mintlify'", apiReady: true, cliAvailable: true, openSource: false, metrics: "2.8K likes; AI-powered docs", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },
  { id: 39, name: "Groq", url: "https://groq.com", xHandle: "GroqInc", founderX: null, devRelX: null, primitive: "AI Model Inference", tier: 3, confidence: "Medium-High", brief: "Ultra-fast LLM inference on custom LPU chips with OpenAI-compatible API and sub-100ms latency.", evidence: "Frequent mentions in agentic tool threads for speed; 'Groq = instant reasoning' hype", apiReady: true, cliAvailable: false, openSource: false, metrics: "Ultra-fast inference", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },
  { id: 40, name: "PocketBase", url: "https://pocketbase.io", xHandle: null, founderX: null, devRelX: null, primitive: "BaaS / Firebase Alternative", tier: 3, confidence: "Medium-High", brief: "Single-file Go backend with embedded SQLite, auth, realtime subscriptions, and admin UI.", evidence: "@fireship_dev OSS alternatives; 'lightweight Firebase replacement'; single binary", apiReady: true, cliAvailable: true, openSource: true, metrics: "35K+ GitHub stars", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },
  { id: 41, name: "Exa", url: "https://exa.ai", xHandle: "exaailabs", founderX: "WilliamBryk", devRelX: null, primitive: "AI Web Scraping", tier: 3, confidence: "Medium-High", brief: "Semantic search API designed for AI agents with embeddings-based web retrieval.", evidence: "@sidi_jeddou_dev: 'best search API for agents and modern apps'; semantic search focus", apiReady: true, cliAvailable: false, openSource: false, metrics: "Best agent search API", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },
  { id: 42, name: "n8n", url: "https://n8n.io", xHandle: "n8n_io", founderX: "janoberhauser", devRelX: null, primitive: "Workflow Automation", tier: 3, confidence: "Medium-High", brief: "Open-source workflow automation with 400+ integrations, code nodes, and self-hosting option.", evidence: "OSS Zapier alternative in multiple high-engagement threads; self-hosted option", apiReady: true, cliAvailable: true, openSource: true, metrics: "40K+ GitHub stars; OSS", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },

  // ============================================
  // TIER 4: Emerging / Strategic (16 partners)
  // ============================================
  { id: 43, name: "LiveKit", url: "https://livekit.io", xHandle: "livekit", founderX: "davidzhao", devRelX: null, primitive: "Voice & Speech AI", tier: 4, confidence: "Medium-High", brief: "Open-source WebRTC infrastructure for real-time video, audio, and data with AI agent support.", evidence: "ThoughtWorks 'Assess'; 12K+ stars; OSS voice/video infra; agent orchestration", apiReady: true, cliAvailable: false, openSource: true, metrics: "12K+ GitHub stars", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: true, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 44, name: "Statsig", url: "https://statsig.com", xHandle: "statsig", founderX: "vijaye", devRelX: null, primitive: "Feature Flags", tier: 4, confidence: "Medium", brief: "Product experimentation platform with feature gates, A/B tests, and real-time analytics.", evidence: "Sequoia portfolio; Madrona IA40 enabler; Vercel Marketplace native integration", apiReady: true, cliAvailable: false, openSource: false, metrics: "Sequoia + Madrona backed", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: true, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 45, name: "Postmark", url: "https://postmarkapp.com", xHandle: "postmarkapp", founderX: null, devRelX: null, primitive: "Transactional Email", tier: 4, confidence: "Medium", brief: "Transactional email API focused on deliverability with 83-99% inbox placement.", evidence: "Best deliverability benchmark (83-99% inbox rate); 3/15 boilerplates", apiReady: true, cliAvailable: false, openSource: false, metrics: "83-99% inbox; 3 boilerplates", launchPartnerOverlap: true, boilerplateCount: 3, vcValidation: false, analystMention: false, benchmarkWinner: true, xHype: false, isNew: false },
  { id: 46, name: "OpenRouter", url: "https://openrouter.ai", xHandle: "openrouterai", founderX: null, devRelX: null, primitive: "Vector DB & AI Infra", tier: 4, confidence: "Medium", brief: "Unified API gateway for 100+ LLMs with automatic fallbacks, cost optimization, and usage tracking.", evidence: "+1,500% YoY Brex #2 fastest-growing; OpenAI-compatible API; multi-model routing", apiReady: true, cliAvailable: false, openSource: false, metrics: "+1,500% YoY (Brex)", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 47, name: "Pinecone", url: "https://pinecone.io", xHandle: "pinaborvanov", founderX: "edoliberty", devRelX: null, primitive: "Vector DB & AI Infra", tier: 4, confidence: "Medium", brief: "Managed vector database for semantic search and RAG with simple API and free starter tier.", evidence: "Market leader by brand; $130M+ raised; free tier (Qdrant outperforms on perf)", apiReady: true, cliAvailable: false, openSource: false, metrics: "$130M+ raised", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 48, name: "Cloudinary", url: "https://cloudinary.com", xHandle: "cloudinary", founderX: null, devRelX: null, primitive: "Storage & Files", tier: 4, confidence: "Medium", brief: "Media management platform with on-the-fly image/video transforms, CDN delivery, and AI features.", evidence: "Netlify partner; AI-powered transforms; industry standard for media management", apiReady: true, cliAvailable: true, openSource: false, metrics: "Netlify/Vercel ecosystem", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 49, name: "Checkly", url: "https://checklyhq.com", xHandle: "checklyHQ", founderX: "tim_nolet", devRelX: null, primitive: "Observability", tier: 4, confidence: "Medium", brief: "Monitoring-as-code platform for API endpoints and browser flows with Playwright tests.", evidence: "Vercel Marketplace partner; monitors API endpoints and browser flows", apiReady: true, cliAvailable: true, openSource: false, metrics: "Vercel Marketplace partner", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 50, name: "Ably", url: "https://ably.com", xHandle: "ablyrealtime", founderX: null, devRelX: null, primitive: "Real-time Messaging", tier: 4, confidence: "Medium", brief: "Enterprise pub/sub infrastructure for real-time messaging with guaranteed delivery and 6M free msgs/mo.", evidence: "Enterprise pub/sub; REST API + SDKs; free 6M msgs/mo; WebSocket infrastructure", apiReady: true, cliAvailable: false, openSource: false, metrics: "6M free msgs/mo", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 51, name: "Weaviate", url: "https://weaviate.io", xHandle: "weaviate_io", founderX: "bobvanluijt", devRelX: null, primitive: "Vector DB & AI Infra", tier: 4, confidence: "Medium", brief: "Open-source vector database with hybrid search, GraphQL API, and multi-modal support.", evidence: "8K+ stars; >1M Docker pulls/mo; strong hybrid search; REST + GraphQL", apiReady: true, cliAvailable: false, openSource: true, metrics: "8K+ stars; >1M Docker pulls", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 52, name: "AssemblyAI", url: "https://assemblyai.com", xHandle: "AssemblyAI", founderX: null, devRelX: null, primitive: "Voice & Speech AI", tier: 4, confidence: "Medium", brief: "Speech-to-text API with speaker diarization, sentiment analysis, and PII redaction built-in.", evidence: "~8% WER; Slam-1 model; PII detection built-in; sentiment analysis; $50 free", apiReady: true, cliAvailable: false, openSource: false, metrics: "$50 free credit", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 53, name: "Socket", url: "https://socket.dev", xHandle: "SocketSecurity", founderX: "feross", devRelX: null, primitive: "Security & Vulnerability", tier: 4, confidence: "Medium", brief: "Supply chain security platform detecting malicious npm/PyPI packages before installation.", evidence: "Rising in X security threads as lightweight Snyk alternative; supply-chain focus", apiReady: true, cliAvailable: true, openSource: false, metrics: "Supply-chain security", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },
  { id: 54, name: "Jina AI", url: "https://jina.ai", xHandle: "JinaAI_", founderX: "hxiao", devRelX: null, primitive: "AI Web Scraping", tier: 4, confidence: "Medium", brief: "Neural search framework for multimodal data with embedding models and RAG components.", evidence: "Appears in semantic search / RAG discussions; neural search & multimodal", apiReady: true, cliAvailable: false, openSource: true, metrics: "Neural search leader", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },
  { id: 55, name: "Make", url: "https://make.com", xHandle: "make_hq", founderX: null, devRelX: null, primitive: "Workflow Automation", tier: 4, confidence: "Medium", brief: "Visual automation platform with advanced data manipulation, branching, and 1,000+ app integrations.", evidence: "Frequently paired with Zapier in 'power user' threads; advanced automation", apiReady: true, cliAvailable: false, openSource: false, metrics: "Power user automation", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: true, isNew: true },
  { id: 56, name: "Dependabot", url: "https://github.com/dependabot", xHandle: "dependabot", founderX: null, devRelX: null, primitive: "Security & Vulnerability", tier: 4, confidence: "Medium", brief: "GitHub-native automated dependency updates with security alerts and PR auto-generation.", evidence: "Ubiquitous in GitHub-native stacks; free for most users; dependency security", apiReady: true, cliAvailable: false, openSource: false, metrics: "GitHub-native; free", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: true },
  { id: 57, name: "Docusaurus", url: "https://docusaurus.io", xHandle: "docusaurus", founderX: null, devRelX: "sebastienlorber", primitive: "Documentation", tier: 4, confidence: "Medium", brief: "Meta's open-source documentation framework with MDX support, versioning, and i18n.", evidence: "Common in 'Mintlify alternative' conversations; Meta-backed; AI plugins emerging", apiReady: true, cliAvailable: true, openSource: true, metrics: "50K+ GitHub stars", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: true },
  { id: 58, name: "Readme.io", url: "https://readme.com", xHandle: "readme", founderX: "gkoberger", devRelX: null, primitive: "Documentation", tier: 4, confidence: "Medium", brief: "Developer hub platform for API documentation with interactive explorer and changelog management.", evidence: "Mentioned in professional docs threads; API documentation platform", apiReady: true, cliAvailable: false, openSource: false, metrics: "API docs platform", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: true },

  // ============================================
  // TIER 5: Strategic Additions / Long-tail (10 partners)
  // ============================================
  { id: 59, name: "Doppler", url: "https://doppler.com", xHandle: "DopplerHQ", founderX: null, devRelX: null, primitive: "Secrets Management", tier: 5, confidence: "Medium", brief: "Universal secrets manager with environment sync across Vercel, Railway, Netlify, and 20+ platforms.", evidence: "CLI + Vercel/Railway/Netlify integrations; team secrets sync", apiReady: true, cliAvailable: true, openSource: false, metrics: "Multi-platform integrations", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 60, name: "PagerDuty", url: "https://pagerduty.com", xHandle: "paborduty", founderX: null, devRelX: null, primitive: "Incident Management", tier: 5, confidence: "Medium", brief: "Industry-standard incident management with on-call scheduling, escalations, and 700+ integrations.", evidence: "Bessemer portfolio success; industry standard alerting; Terraform provider", apiReady: true, cliAvailable: true, openSource: false, metrics: "Industry standard", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: true, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 61, name: "Knock", url: "https://knock.app", xHandle: "knocklabs", founderX: null, devRelX: null, primitive: "Notifications", tier: 5, confidence: "Medium", brief: "Enterprise notification infrastructure with workflow orchestration, batching, and preferences API.", evidence: "Enterprise-grade workflow orchestration; batching/digests; $250/mo starter", apiReady: true, cliAvailable: false, openSource: false, metrics: "$250/mo starter", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 62, name: "Paddle", url: "https://paddle.com", xHandle: "PaddleHQ", founderX: null, devRelX: null, primitive: "Payments", tier: 5, confidence: "Medium", brief: "Merchant of Record handling global tax compliance, subscriptions, and checkout for SaaS.", evidence: "4/15 boilerplates (Laravel ecosystem default); MoR (tax handling); SaaS-focused", apiReady: true, cliAvailable: false, openSource: false, metrics: "4 boilerplates; MoR", launchPartnerOverlap: false, boilerplateCount: 4, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 63, name: "Temporal", url: "https://temporal.io", xHandle: "temporalio", founderX: "maborev", devRelX: null, primitive: "Workers & Background Jobs", tier: 5, confidence: "Medium", brief: "Durable execution platform for long-running workflows with automatic state persistence and retries.", evidence: "12K+ stars; enterprise durable execution; multi-language; Cloud + self-host", apiReady: true, cliAvailable: true, openSource: true, metrics: "12K+ GitHub stars", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 64, name: "Polar", url: "https://polar.sh", xHandle: "polar_sh", founderX: "birk", devRelX: null, primitive: "Payments", tier: 5, confidence: "Medium", brief: "Open-source monetization platform for developers with subscriptions, benefits, and GitHub integration.", evidence: "2/15 boilerplates; 3K+ stars; developer-first OSS monetization; Next.js adapter", apiReady: true, cliAvailable: false, openSource: true, metrics: "3K+ stars; 2 boilerplates", launchPartnerOverlap: false, boilerplateCount: 2, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 65, name: "UploadThing", url: "https://uploadthing.com", xHandle: "pingdotgg", founderX: "t3dotgg", devRelX: null, primitive: "Storage & Files", tier: 5, confidence: "Medium", brief: "Type-safe file uploads for Next.js, Astro, Svelte, and Nuxt with built-in CDN.", evidence: "T3 ecosystem; 4K+ stars (MIT); Next.js/Astro/Svelte/Nuxt support", apiReady: true, cliAvailable: false, openSource: true, metrics: "4K+ stars; T3 ecosystem", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 66, name: "Loops", url: "https://loops.so", xHandle: "loops_so", founderX: "frantzfries", devRelX: null, primitive: "Email Marketing", tier: 5, confidence: "Medium", brief: "API-first email marketing for SaaS with product-led sequences, broadcasts, and transactional.", evidence: "API-first; product-led email; growing in indie/SaaS community", apiReady: true, cliAvailable: false, openSource: false, metrics: "Growing indie adoption", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 67, name: "Dub", url: "https://dub.co", xHandle: "dubdotco", founderX: "steventey", devRelX: null, primitive: "Link Management", tier: 5, confidence: "Medium", brief: "Open-source link management with custom domains, analytics, and API for short URLs.", evidence: "20K+ stars; OSS; REST API; developer-first short links/analytics", apiReady: true, cliAvailable: false, openSource: true, metrics: "20K+ GitHub stars", launchPartnerOverlap: false, boilerplateCount: 0, vcValidation: false, analystMention: false, benchmarkWinner: false, xHype: false, isNew: false },
  { id: 68, name: "Convex", url: "https://convex.dev", xHandle: "convabordev", founderX: null, devRelX: null, primitive: "Reactive Backend", tier: 5, confidence: "Medium", brief: "TypeScript-first backend with real-time sync, automatic caching, and serverless functions.", evidence: "ThoughtWorks 'Assess'; TypeScript-first; real-time sync; SDK + CLI", apiReady: true, cliAvailable: true, openSource: false, metrics: "Fast growth", launchPartnerOverlap: true, boilerplateCount: 0, vcValidation: false, analystMention: true, benchmarkWinner: false, xHype: false, isNew: false },
];

// Derived filter options (auto-generated from data)
const PRIMITIVES = [...new Set(PARTNERS.map(p => p.primitive))].sort();
const TIERS = [...new Set(PARTNERS.map(p => p.tier))].sort((a, b) => a - b);
const CONFIDENCE_LEVELS = ["Very High", "High", "Medium-High", "Medium"];

// Export for module usage (if needed)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PARTNERS, PRIMITIVES, TIERS, CONFIDENCE_LEVELS, DATA_VERSION };
}
