#!/usr/bin/env python3
"""
Fetch the self-hosted webfonts used by the Remotion syllabus film.

Remotion renders in a headless Chromium that has no Inter, no Source Serif and
no JetBrains Mono installed, and a render that reaches out to fonts.gstatic.com
mid-frame is a render that can produce different typography on two different
days. So the latin subsets are vendored into /public/fonts and loaded from
disk by remotion/src/theme.ts.

Google serves these three families as variable fonts: every requested weight
resolves to the same file, so one file per family is downloaded and exposed
through a `font-weight` range.

Usage:
    python3 scripts/fetch_video_fonts.py
"""

import os
import re
import ssl
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "public", "fonts")

# Chrome UA, or the CSS API answers with truetype rather than woff2.
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

# family spec -> (local basename, weight range exposed to CSS)
FAMILIES = [
    ("Source+Serif+4:wght@400;600;700", "SourceSerif4", "400 700"),
    ("Inter:wght@400;500;600;700", "Inter", "400 700"),
    ("JetBrains+Mono:wght@500", "JetBrainsMono", "500"),
]

# The film is English-only; the latin block is the only subset worth shipping.
LATIN_RANGE = "U+0000-00FF"


def context():
    bundle = "/root/.ccr/ca-bundle.crt"
    if os.path.exists(bundle):
        return ssl.create_default_context(cafile=bundle)
    return ssl.create_default_context()


CONTEXT = context()


def get(url):
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, context=CONTEXT, timeout=60) as response:
        return response.read()


def latin_face(css):
    """The @font-face block covering basic latin, with its family name."""
    for block in re.findall(r"@font-face \{(.*?)\}", css, re.S):
        if LATIN_RANGE not in block:
            continue
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        url = re.search(r"url\((https://[^)]+)\)", block).group(1)
        return family, url
    raise RuntimeError("no latin @font-face block in the returned CSS")


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    rules = []

    for spec, basename, weight in FAMILIES:
        css = get(
            f"https://fonts.googleapis.com/css2?family={spec}&display=swap"
        ).decode("utf-8")
        family, url = latin_face(css)
        payload = get(url)

        filename = f"{basename}-latin.woff2"
        with open(os.path.join(OUT_DIR, filename), "wb") as handle:
            handle.write(payload)
        print(f"{filename}  {len(payload) / 1024:.1f} KB")

        rules.append(
            "@font-face {\n"
            f"  font-family: '{family}';\n"
            "  font-style: normal;\n"
            f"  font-weight: {weight};\n"
            "  font-display: block;\n"
            f"  src: url('./{filename}') format('woff2');\n"
            "}\n"
        )

    header = (
        "/* Latin subsets for the Remotion syllabus film.\n"
        " * Generated by scripts/fetch_video_fonts.py — do not edit by hand. */\n\n"
    )
    with open(os.path.join(OUT_DIR, "fonts.css"), "w", encoding="utf-8") as handle:
        handle.write(header + "\n".join(rules))
    print(f"\nwrote {os.path.join(OUT_DIR, 'fonts.css')}")


if __name__ == "__main__":
    main()
